apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: {{ .Values.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: {{ .Values.nginx.replicaCount }}
  maxReplicas: {{ .Values.nginx.hpa.maxReplicas }}
  metrics:
  {{- if .Values.nginx.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.nginx.hpa.cpu }}
  {{- end }}
  {{- if .Values.nginx.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.nginx.hpa.memory }}
  {{- end }}
  {{- if .Values.nginx.hpa.requests }}
  - type: Pod
      pods:
        metricName: http_requests
        targetAverageValue: {{ .Values.nginx.hpa.requests }}
  {{- end }}
