apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.Deployment.Name }}-secrets"
  namespace: {{ .Values.Namespace }}
type: "kubernetes.io/opaque"
data:
  {{- range $key, $val := .Values.Secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
